
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "starpi.fullname" . }}
  labels:
    app: {{ template "starpi.name" . }}
    chart: {{ template "starpi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: {{ template "starpi.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaling.cpu.targetPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.memory.enabled }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.autoscaling.memory.targetPercentage }}
  {{- end }}
{{- end  }}