{{- if .Values.ingress.enabled -}}
{{- $fullName := include "starpi.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "starpi.name" . }}
    chart: {{ template "starpi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{- range .Values.ingress.tls }}
    {{- if .hosts }}
    - hosts:
    {{- range .hosts }}
      - {{ . }}
    {{- end }}
    {{- end }}
    secretName: {{ .secretName }}
{{- end }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
  {{- end }}
{{- end }}